### ISSUE TITLE
Displaying "behind" and "ahead" commits count

### ISSUE THREAD

**Issue by payne911** [jkunstwald/useful-forks#1]
This is actually 2 feature requests, but I only really would love to see the first one:

1. A counter of the commits difference compared to the original (how many commits ahead and `behind` of `master`).
2. Toggle ON/OFF the info displayed (Watchers, Stars, Forks, Commits-Diff).

**Comment by jkunstwald** [comment]
I got around to implement this and made some changes to the CSS as well, it now looks like this:

![useful_v1_1](https://user-images.githubusercontent.com/17261478/97032534-47c4f300-1562-11eb-928e-8a9b1ad75e26.PNG)

The commits ahead/behind requires a separate API query per fork, thus they do not load immediately and get added one-by-one. As for the settings, they are not quite as straightforward to implement and would require some additional UI and storage, so i skipped that for now. Thank you for the suggestion!

**Comment by payne911** [comment]
@jkunstwald Hey, I wasn't sure if you were still active so I forked your repo: you should check out what I've done.  :)

I ended up making an organization and a website for it:

- https://github.com/useful-forks/useful-forks.github.io
- https://useful-forks.github.io

The thing's about to be featured on ``refined-github``: https://github.com/sindresorhus/refined-github/issues/3682

I applied the MIT license to the project: can you confirm that this was fine?

I'll gladly add you as an owner on the organization, if you want to collaborate on this. I like your latest CSS for the badges. :)

By the way, my latest issues were:

1. https://stackoverflow.com/questions/64503732/github-api-compare-two-commits-unclear
2. https://github.com/useful-forks/useful-forks.github.io/issues/1

And I was planning on adding the logo and some introductory/explanatory text below the text field on the website, tonight.

**Comment by jkunstwald** [comment]
Oh neat, i see! So you're doing a recursive search for other forks? I wonder if you'd hit API rate limiting issues with that many requests. 

MIT is just fine. I don't have a lot of time currently to work on projects like this one, so im glad you're having fun with it.

**Comment by payne911** [comment]
> Oh neat, i see! So you're doing a recursive search for other forks? I wonder if you'd hit API rate limiting issues with that many requests.

It does happen, that's why I tried to facilitate providing an Access Token.

Try it out, you'll see for yourself: https://useful-forks.github.io/?repository=EsotericSoftware/kryonet
